import { chromium, expect } from '@playwright/test';
import { mkdir } from 'node:fs/promises';

// Run against an already running Vite server. Uses a fresh browser context;
// never attaches to the user's browser or sends real emails.
const browser = await chromium.launch({ executablePath: process.env.CHROMIUM_PATH || '/usr/bin/chromium', headless: true });
const context = await browser.newContext({ viewport: { width: 1440, height: 1100 }, locale: 'vi-VN' });
const page = await context.newPage();
const errors = [];
page.on('pageerror', error => errors.push(error.message));
const shots = new URL('../docs/screenshots/', import.meta.url).pathname;
await mkdir(shots, { recursive: true });
const nav = name => page.getByRole('navigation', { name: 'Điều hướng chính' }).getByRole('button', { name, exact: true });
const role = async (value) => {
  await page.getByRole('combobox', { name: 'Đổi vai demo' }).selectOption(value);
  const skip = page.getByRole('button', { name: 'Bỏ qua', exact: true });
  if (await skip.isVisible({ timeout: 500 }).catch(() => false)) await skip.click();
};
const requestCard = () => page.locator('.request-card').filter({ hasText: 'Kịch bản kiểm thử giao nhận sách' });
try {
  await page.goto(process.env.TEST_URL || 'http://127.0.0.1:5173/', { waitUntil: 'domcontentloaded' });
  const welcome = page.getByRole('dialog', { name: 'Lời chào từ người đề xuất ý tưởng' });
  await expect(welcome).toBeVisible();
  await expect(welcome).toContainText('Nguyễn Xuân Hiếu');
  await expect(welcome).toContainText('được AI xây dựng theo yêu cầu của em');
  const readmeUrl = new URL(await welcome.getByRole('link', { name: 'Tải README.md' }).getAttribute('href'), page.url());
  const readme = await page.request.get(readmeUrl.toString());
  expect(readme.ok()).toBe(true);
  expect(await readme.text()).toContain('Tải và chạy trên máy của người xem');
  await page.screenshot({ path: `${shots}00-loi-chao.png`, fullPage: true });
  await page.getByRole('button', { name: 'Tiếp tục khám phá' }).click();
  await expect(page.getByRole('dialog', { name: 'Chào mừng đến Cầu Sách' })).toBeVisible();
  await page.screenshot({ path: `${shots}01-gioi-thieu.png`, fullPage: true });
  await page.getByRole('button', { name: 'Mình đã hiểu, bắt đầu thôi' }).click();
  await page.getByLabel('Mật khẩu demo').fill('wrong');
  await page.getByRole('button', { name: 'Vào góc học tập' }).click();
  await expect(page.getByRole('alert')).toContainText('demo2026');
  await page.getByLabel('Mật khẩu demo').fill('demo2026');
  await page.getByRole('button', { name: 'Vào góc học tập' }).click();
  await expect(page.getByRole('dialog', { name: 'Bắt đầu từ một cuốn sách' })).toBeVisible();
  await page.keyboard.press('Tab');
  expect(await page.evaluate(() => !!document.activeElement.closest('.tour-card'))).toBe(true);
  for (let i = 0; i < 4; i++) await page.getByRole('button', { name: 'Tiếp theo', exact: true }).click();
  await page.getByRole('button', { name: 'Khám phá thôi', exact: true }).click();
  await expect(page.locator('.hero')).toBeVisible();
  await page.screenshot({ path: `${shots}02-tu-sach-desktop.png`, fullPage: true });
  await page.getByRole('textbox', { name: 'Tìm sách', exact: true }).fill('vat li');
  await expect(page.locator('.book-card')).toHaveCount(1);
  await expect(page.locator('.book-card h3')).toHaveText('Vật lí 10');
  await expect(page.locator('.book-card a')).toHaveAttribute('href', 'https://hanhtrangso.nxbgd.vn/');
  await page.getByRole('button', { name: 'Xóa', exact: true }).click();
  console.log('PASS: intro, login validation, 5-step keyboard-accessible tour, catalog filters and official link');

  await page.getByRole('button', { name: 'Cài đặt tài khoản', exact: true }).click();
  await page.getByLabel('Email cá nhân').fill('minhan@example.com');
  await page.getByLabel('Nhận thông báo qua email').check();
  await page.getByRole('button', { name: 'Lưu cài đặt' }).click();
  await nav('Mượn sách').click();
  await page.getByRole('button', { name: 'Tạo yêu cầu mượn', exact: true }).first().click();
  await page.getByLabel('Lời nhắn').fill('Kịch bản kiểm thử giao nhận sách');
  await page.getByRole('button', { name: 'Gửi yêu cầu', exact: true }).click();
  await expect(requestCard()).toBeVisible();
  await role('linh');
  await nav(/Cho mượn/).click();
  await expect(requestCard()).toContainText('lịch học phù hợp');
  await requestCard().getByRole('button', { name: 'Mình có thể cho mượn' }).click();
  await page.getByRole('button', { name: 'Gửi đề nghị', exact: true }).click();
  await expect(requestCard()).toContainText('Chờ người mượn xác nhận');
  await role('an'); await nav('Mượn sách').click();
  await requestCard().getByRole('button', { name: 'Xác nhận mượn' }).click();
  await expect(requestCard()).toContainText('Đã xác nhận');
  await expect(requestCard()).toContainText('Phòng 202');
  await page.screenshot({ path: `${shots}03-muon-sach-desktop.png`, fullPage: true });
  await requestCard().getByRole('button', { name: 'Mình đã nhận sách' }).click();
  await role('linh'); await nav(/Cho mượn/).click();
  await expect(requestCard()).toHaveCount(0);
  await page.getByRole('button', { name: /Tôi đã đề nghị/ }).click();
  await requestCard().getByRole('button', { name: 'Xác nhận đã nhận lại sách' }).click();
  await expect(requestCard()).toContainText('Đã trả sách');
  await role('an'); await nav('Mượn sách').click();
  await page.getByRole('button', { name: /Lịch sử/ }).click();
  await expect(requestCard()).toContainText('Đã trả sách');
  await page.getByRole('button', { name: /^Thông báo/ }).click();
  await page.getByRole('button', { name: /Hộp thư mô phỏng/ }).click();
  await expect(page.locator('.mail-card').first()).toContainText('minhan@example.com');
  await page.reload({ waitUntil: 'domcontentloaded' });
  await page.getByRole('button', { name: 'Tiếp tục khám phá' }).click();
  await expect(page.locator('.hero')).toBeVisible();
  expect(await page.evaluate(() => JSON.parse(localStorage.getItem('cau-sach:v1')).requests.some(r => r.note === 'Kịch bản kiểm thử giao nhận sách' && r.status === 'returned'))).toBe(true);
  console.log('PASS: create, targeted matching, offer, confirm, receive, return, mail simulation, reload persistence');

  await nav('Mượn sách').click();
  await page.getByRole('button', { name: 'Tạo yêu cầu mượn', exact: true }).first().click();
  await page.getByRole('radio', { name: /Thư viện/ }).check();
  await page.getByLabel('Lời nhắn').fill('Yêu cầu thư viện kiểm thử');
  await page.getByRole('button', { name: 'Gửi yêu cầu', exact: true }).click();
  await role('guest'); await nav(/Cho mượn/).click();
  await expect(page.locator('.request-card').filter({ hasText: 'Yêu cầu thư viện kiểm thử' })).toHaveCount(0);
  await nav('Mượn sách').click();
  await page.getByRole('button', { name: 'Tạo yêu cầu mượn', exact: true }).first().click();
  await expect(page.getByRole('radio', { name: /Thư viện/ })).toBeDisabled();
  await page.getByRole('button', { name: 'Để sau', exact: true }).click();
  await nav('Thời khóa biểu').click();
  await expect(page.getByText('Lịch học dành cho tài khoản trường')).toBeVisible();
  await role('library'); await nav(/Cho mượn/).click();
  const libCard = page.locator('.request-card').filter({ hasText: 'Yêu cầu thư viện kiểm thử' });
  await libCard.getByRole('button', { name: 'Mình có thể cho mượn' }).click();
  await expect(page.getByLabel('Địa điểm nhận và trả trong trường')).toHaveValue('Phòng thư viện · Tầng 1, khu A');
  await page.getByRole('button', { name: 'Gửi đề nghị', exact: true }).click();
  const physicsCard = page.locator('.request-card').filter({ hasText: 'Em xin mượn sách cho tiết Vật lí.' });
  await expect(physicsCard.getByRole('button', { name: 'Không còn bản khả dụng' })).toBeDisabled();
  await physicsCard.getByRole('button', { name: /Từ chối/ }).click();
  await expect(physicsCard).toHaveCount(0);
  await role('an'); await nav('Mượn sách').click();
  await libCard.getByRole('button', { name: 'Xác nhận mượn' }).click();
  await expect(libCard).toContainText('Miễn phí');
  await libCard.getByRole('button', { name: 'Hủy yêu cầu / Đã có sách' }).click();
  await page.getByRole('button', { name: 'Xác nhận hủy', exact: true }).click();
  await expect(libCard).toHaveCount(0);
  console.log('PASS: library privacy, guest limits, library zero-stock rejection, free loan, cancellation');

  await page.getByRole('button', { name: 'Đăng xuất', exact: true }).click();
  await page.getByRole('button', { name: 'Tạo tài khoản khách', exact: true }).click();
  await page.getByLabel('Tên hiển thị').fill('Khách Demo Mới');
  await page.getByLabel('Tên đăng nhập').fill('khachmoi');
  await page.getByRole('checkbox').check();
  await page.getByRole('button', { name: 'Tạo tài khoản & bắt đầu' }).click();
  await page.getByRole('button', { name: 'Bỏ qua', exact: true }).click();
  await expect(page.locator('.hero')).toBeVisible();
  await page.getByRole('button', { name: 'Cài đặt tài khoản', exact: true }).click();
  await expect(page.getByText('@khachmoi · Tài khoản khách')).toBeVisible();
  await nav(/Cho mượn/).click();
  await page.getByRole('button', { name: 'Sách mình có (0)' }).click();
  await page.getByRole('checkbox', { name: 'Tôi có Toán 10' }).check();
  await page.getByRole('button', { name: 'Xong', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Sách mình có (1)' })).toBeVisible();
  console.log('PASS: guest registration and copy ownership');

  await role('an');
  await page.evaluate(() => {
    const db = JSON.parse(localStorage.getItem('cau-sach:v1'));
    const r = db.requests.find(r => r.borrowerId === 'an' && r.status === 'open');
    r.date = '2020-01-06'; r.note = 'Yêu cầu hết hạn tự động kiểm thử';
    localStorage.setItem('cau-sach:v1', JSON.stringify(db));
  });
  await page.reload({ waitUntil: 'domcontentloaded' });
  await page.getByRole('button', { name: 'Tiếp tục khám phá' }).click();
  await nav('Mượn sách').click();
  await expect(page.locator('.request-card').filter({ hasText: 'Yêu cầu hết hạn tự động kiểm thử' })).toHaveCount(0);
  await page.getByRole('button', { name: /Lịch sử/ }).click();
  await expect(page.locator('.request-card').filter({ hasText: 'Yêu cầu hết hạn tự động kiểm thử' })).toContainText('Hết hạn');
  await nav('Sách online').click();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: `${shots}04-tu-sach-mobile.png`, fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await nav(/Cho mượn/).click();
  await page.screenshot({ path: `${shots}05-cho-muon-mobile.png`, fullPage: true });
  await nav('Thời khóa biểu').click();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.setViewportSize({ width: 320, height: 740 });
  await nav('Sách online').click();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.getByRole('button', { name: 'Cài đặt tài khoản', exact: true }).click();
  await page.getByRole('button', { name: 'Đăng xuất khỏi tài khoản', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Vào góc học tập' })).toBeVisible();
  expect(errors).toEqual([]);
  console.log('PASS: automatic expiry, mobile 390/320px, no horizontal page overflow, no runtime errors');
  console.log(`Screenshots saved to ${shots}`);
} finally { await browser.close(); }
