import { useState } from 'react';
import { ArrowRight, BookOpen, Check, ExternalLink, HeartHandshake, LibraryBig, Search, ShieldCheck, SlidersHorizontal } from 'lucide-react';
import { books } from '../catalog';
import { BookArt, Empty, HeroArt } from '../components';
import { useApp } from '../context';

export function BooksPage() {
  const { db, user, go } = useApp(); const [search, setSearch] = useState(''); const [subject, setSubject] = useState('');
  const normalize = (s: string) => s.toLocaleLowerCase('vi').normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/đ/g, 'd');
  const filtered = books.filter(b => (!subject || b.subject === subject) && normalize(`${b.title} ${b.series} ${b.volume}`).includes(normalize(search)));
  const openCount = db.requests.filter(r => r.target === 'community' && r.status === 'open').length;
  return <>
    <div className="welcome-line"><span>GÓC HỌC TẬP CỦA BẠN</span><span className="subtle-label"><span className="live-dot" /> Cùng nhau sẵn sàng cho buổi học tới</span></div>
    <section className="hero"><div className="hero-copy"><span className="hero-pill"><span className="live-dot" /> MỞ SÁCH · MỞ CƠ HỘI</span><h1>Sách chưa về,<br />việc học <em>vẫn tiếp nối.</em></h1><p>Đọc sách từ nguồn chính thức hoặc tìm một cuốn sách<br className="desktop-break" /> để mượn. Luôn có một cách để bạn học tiếp.</p><div className="hero-actions"><button className="button cream" onClick={() => document.getElementById('catalog')?.scrollIntoView({ behavior: 'smooth', block: 'start' })}>Khám phá sách <ArrowRight size={17} /></button><button className="hero-link" onClick={() => go('borrow')}>Mình cần mượn sách <ArrowRight size={16} /></button></div></div><HeroArt /><span className="hero-caption">Chia sẻ tri thức, tiếp nối tương lai.</span></section>
    <div className="quick-grid"><div className="quick-item"><span className="quick-icon"><ShieldCheck size={24} /></span><div><strong>Nguồn sách chính thức</strong><p>Truy cập trực tiếp từ nhà xuất bản</p></div></div><button className="quick-item" onClick={() => go('lend')}><span className="quick-icon peach-icon"><HeartHandshake size={25} /></span><div><strong>{openCount} lời nhờ mượn đang chờ</strong><p>Một cuốn sách có thể giúp một người bạn</p></div><ArrowRight size={17} /></button><button className="quick-item" onClick={() => go(user.role === 'library' ? 'lend' : 'borrow')}><span className="quick-icon blue-icon"><LibraryBig size={24} /></span><div><strong>Thư viện cùng đồng hành</strong><p>Mượn sách tại trường, hoàn toàn miễn phí</p></div><ArrowRight size={17} /></button></div>
    <section id="catalog" className="catalog-section"><div className="catalog-heading"><div><span className="eyebrow">TÌM ĐÚNG SÁCH, HỌC ĐÚNG BÀI</span><h2>Tủ sách online<span className="count-pill">{books.length} đầu sách mẫu</span></h2><p>Chọn cuốn sách bạn cần. Cầu Sách đưa bạn đến nguồn chính thức.</p></div><span className="source-label"><Check size={14} /> Nguồn do trường duyệt</span></div>
      <div className="filter-bar"><div className="search-field"><Search size={19} /><input aria-label="Tìm sách" placeholder="Tìm tên sách, môn học hoặc bộ sách…" value={search} onChange={e => setSearch(e.target.value)} />{search && <button className="text-button" onClick={() => setSearch('')}>Xóa</button>}</div><label className="filter-select"><span>Khối lớp</span><select aria-label="Khối lớp"><option>Lớp 10</option></select></label><label className="filter-select"><span>Môn học</span><select aria-label="Môn học" value={subject} onChange={e => setSubject(e.target.value)}><option value="">Tất cả môn</option>{books.map(b => <option key={b.id}>{b.subject}</option>)}</select></label><span className="filter-mark"><SlidersHorizontal size={18} /></span></div>
      <div className="catalog-meta"><span>Hiển thị <b>{filtered.length}</b> đầu sách</span><span>Kết nối tri thức với cuộc sống · Lớp 10</span></div>
      {filtered.length ? <div className="book-grid">{filtered.map(book => <article className="book-card" key={book.id}><BookArt book={book} /><div className="book-card-body"><span className="book-series">KẾT NỐI TRI THỨC VỚI CUỘC SỐNG</span><h3>{book.title}</h3><div className="book-meta"><span>Lớp {book.grade}</span><span>·</span><span>{book.volume}</span></div><a className="book-open" href={book.url} target="_blank" rel="noopener noreferrer" aria-label={`Tìm ${book.title} tại Hành trang số`}>Mở nguồn chính thức <ExternalLink size={15} /></a></div></article>)}</div> : <Empty title="Chưa tìm thấy sách phù hợp" text="Thử tên môn học khác hoặc xóa bộ lọc để xem lại danh mục."><button className="button secondary" onClick={() => { setSearch(''); setSubject(''); }}>Xóa bộ lọc</button></Empty>}
      <div className="source-footnote"><ShieldCheck size={18} /><p>Đường dẫn mở kho <a href="https://hanhtrangso.nxbgd.vn/" target="_blank" rel="noopener noreferrer">Hành trang số — NXBGD Việt Nam</a>; chọn đúng lớp, bộ sách và tập tại đó. Một số nội dung có thể yêu cầu đăng nhập. Hình trên là minh họa do Cầu Sách tạo, không phải bìa sách chính thức.</p></div></section>
    <div className="bottom-callout"><span className="callout-icon"><BookOpen size={28} /></span><div><h3>Thích một cuốn sách trên tay hơn?</h3><p>Đăng yêu cầu mượn trước buổi học để bạn bè và thư viện kịp hỗ trợ.</p></div><button className="button secondary" onClick={() => go(user.role === 'library' ? 'lend' : 'borrow')}>{user.role === 'library' ? 'Xem yêu cầu' : 'Tìm sách để mượn'}<ArrowRight size={16} /></button></div>
  </>;
}
