import { useState } from 'react';
import type { FormEvent } from 'react';
import { ArrowRight, CalendarDays, Check, Clock3, HeartHandshake, LibraryBig, MapPin, Plus, Search, Send, Users } from 'lucide-react';
import type { BorrowRequest, RequestStatus } from '../types';
import { acceptOffer, available, changeRequest, createRequest, endAt, matchesSchedule, nextSchoolDate, offerBook, periods, toggleOwned, vnDate } from '../domain';
import { books } from '../catalog';
import { useApp } from '../context';
import { Empty, Modal, SectionHeading } from '../components';

const statusNames: Record<RequestStatus, string> = { open: 'Đang tìm sách', matched: 'Đã xác nhận', received: 'Đang mượn', returned: 'Đã trả sách', expired: 'Hết hạn', cancelled: 'Đã hủy', rejected: 'Thư viện từ chối' };
export const formatDate = (date: string) => new Intl.DateTimeFormat('vi-VN', { weekday: 'short', day: '2-digit', month: '2-digit', timeZone: 'Asia/Ho_Chi_Minh' }).format(new Date(`${date}T12:00:00+07:00`));
export function BorrowPage() {
  const { db, user, go } = useApp(); const [create, setCreate] = useState(false); const [tab, setTab] = useState('active');
  const mine = db.requests.filter(r => r.borrowerId === user.id); const live = (r: BorrowRequest) => ['open', 'matched', 'received'].includes(r.status);
  const shown = mine.filter(r => tab === 'active' ? live(r) : !live(r));
  if (user.role === 'library') return <><SectionHeading eyebrow="GÓC THƯ VIỆN" title="Kết nối sách với người cần" text="Tài khoản thư viện xử lý yêu cầu và quản lý số bản sách trong mục Cho mượn." /><Empty title="Cùng hỗ trợ học sinh" text="Xem các yêu cầu được học sinh gửi trực tiếp tới thư viện."><button className="button primary" onClick={() => go('lend')}>Đến bàn thư viện <ArrowRight size={16} /></button></Empty></>;
  return <><SectionHeading eyebrow="MỘT LỜI NHỜ · MỘT KẾT NỐI" title="Mượn sách" text="Chuẩn bị cho buổi học tới, với sự giúp đỡ của bạn bè và thư viện."><button className="button primary" onClick={() => setCreate(true)}><Plus size={18} /> Tạo yêu cầu mượn</button></SectionHeading>
    <div className="steps-strip"><div><span>01</span><p><strong>Chọn sách & lịch học</strong>Gửi yêu cầu trước buổi học</p></div><ArrowRight /><div><span>02</span><p><strong>Chọn lời đề nghị</strong>Xác nhận để giữ sách</p></div><ArrowRight /><div><span>03</span><p><strong>Gặp nhau & học tiếp</strong>Nhận, giữ gìn và trả đúng hẹn</p></div></div>
    {user.role === 'guest' && <div className="info-box">Bạn đang dùng tài khoản khách: mượn trong cộng đồng và nhận thông báo giao dịch. Gửi yêu cầu thư viện và gợi ý theo thời khóa biểu dành cho tài khoản trường.</div>}
    <div className="tabs"><button className={tab === 'active' ? 'active' : ''} onClick={() => setTab('active')}>Đang theo dõi <span>{mine.filter(live).length}</span></button><button className={tab === 'history' ? 'active' : ''} onClick={() => setTab('history')}>Lịch sử <span>{mine.filter(r => !live(r)).length}</span></button></div>
    <div className="requests-grid">{shown.map(r => <RequestCard key={r.id} request={r} />)}</div>{!shown.length && <Empty title={tab === 'active' ? 'Buổi học tới, bạn cần sách gì?' : 'Lịch sử còn đang để trống'} text={tab === 'active' ? 'Tạo yêu cầu đầu tiên. Bạn bè và thư viện sẽ cùng tìm cách hỗ trợ.' : 'Yêu cầu đã trả, hết hạn hoặc đã hủy sẽ được lưu ở đây.'}>{tab === 'active' && <button className="button primary" onClick={() => setCreate(true)}>Tạo yêu cầu mượn <Plus size={17} /></button>}</Empty>}
    {create && <RequestForm onClose={() => setCreate(false)} />}
  </>;
}
function RequestForm({ onClose }: { onClose: () => void; }) {
  const { user, commit } = useApp(); const [date, setDate] = useState(nextSchoolDate()); const [start, setStart] = useState(1); const [end, setEnd] = useState(2); const [target, setTarget] = useState<'community' | 'library'>('community');
  function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const form = new FormData(e.currentTarget); if (commit(db => createRequest(db, user.id, { bookId: String(form.get('bookId')), date, start, end, target, note: String(form.get('note')) }), 'Yêu cầu đã được gửi. Theo dõi các lời đề nghị trong mục Mượn sách.')) onClose(); }
  return <Modal title="Bạn cần mượn sách gì?" onClose={onClose}><p className="muted">Gửi sớm trước buổi học để mọi người kịp chuẩn bị nhé.</p><form onSubmit={submit}><label>Sách cần mượn<select name="bookId" required>{books.map(b => <option key={b.id} value={b.id}>{b.title} · {b.volume} · {b.series}</option>)}</select></label><label>Ngày mượn<input type="date" value={date} min={vnDate()} onChange={e => setDate(e.target.value)} required /></label><div className="form-row"><label>Từ tiết<select value={start} onChange={e => { const value = Number(e.target.value); setStart(value); if (end < value) setEnd(value); }}>{periods.map((p, i) => <option value={i + 1} key={i}>Tiết {i + 1} · {p.start}</option>)}</select></label><label>Đến hết tiết<select value={end} onChange={e => setEnd(Number(e.target.value))}>{periods.map((p, i) => <option value={i + 1} key={i} disabled={i + 1 < start}>Tiết {i + 1} · {p.end}</option>)}</select></label></div><div className="schedule-summary"><Clock3 size={17} /><span>Nhận trước {periods[start - 1].start}, trả lúc {periods[end - 1].end} · Giờ Việt Nam</span></div><fieldset className="target-options"><legend>Gửi yêu cầu đến</legend><label className={target === 'community' ? 'chosen' : ''}><input type="radio" name="target" checked={target === 'community'} onChange={() => setTarget('community')} /><Users size={20} /><span>Cộng đồng<small>10.000đ/lượt · trả trực tiếp</small></span></label><label className={`${target === 'library' ? 'chosen' : ''} ${user.role === 'guest' ? 'disabled' : ''}`}><input type="radio" name="target" checked={target === 'library'} disabled={user.role === 'guest'} onChange={() => setTarget('library')} /><LibraryBig size={20} /><span>Thư viện<small>{user.role === 'guest' ? 'Cần tài khoản trường' : 'Miễn phí · nhận tại trường'}</small></span></label></fieldset><label>Lời nhắn <span className="optional">(không bắt buộc)</span><textarea name="note" maxLength={240} rows={3} placeholder="Nhắn một chút về thời gian, cách nhận sách…" /></label><p className="fine">{target === 'community' ? 'Mọi người thấy yêu cầu trong mục Cho mượn. Chỉ học sinh có sách và lịch phù hợp được nhận gợi ý tự động.' : 'Yêu cầu chỉ được gửi tới thư viện trường và không xuất hiện trên bảng cộng đồng.'} Yêu cầu chưa được xác nhận sẽ ẩn khi hết tiết cuối.</p><div className="modal-actions"><button className="button secondary" type="button" onClick={onClose}>Để sau</button><button className="button primary" type="submit">Gửi yêu cầu <Send size={16} /></button></div></form></Modal>;
}
export function LendPage() {
  const { db, user, commit } = useApp(); const [tab, setTab] = useState('board'); const [bookFilter, setBookFilter] = useState(''); const [dateFilter, setDateFilter] = useState(''); const [periodFilter, setPeriodFilter] = useState(''); const [ownedOpen, setOwnedOpen] = useState(false); const isLibrary = user.role === 'library';
  const board = db.requests.filter(r => r.status === 'open' && r.target === (isLibrary ? 'library' : 'community'));
  const history = db.requests.filter(r => isLibrary ? r.target === 'library' && r.status !== 'open' : db.offers.some(o => o.requestId === r.id && o.lenderId === user.id));
  const shown = (tab === 'board' ? board : history).filter(r => (!bookFilter || r.bookId === bookFilter) && (!dateFilter || r.date === dateFilter) && (!periodFilter || r.start <= Number(periodFilter) && r.end >= Number(periodFilter)));
  return <><SectionHeading eyebrow={isLibrary ? 'BÀN THƯ VIỆN' : 'CHIA SẺ MỘT CUỐN SÁCH'} title={isLibrary ? 'Thư viện đồng hành' : 'Cho mượn sách'} text={isLibrary ? 'Xử lý yêu cầu gửi thư viện và giúp học sinh sẵn sàng cho buổi học.' : 'Cuốn sách bạn đang có, có thể là điều một người bạn đang cần.'}><button className="button secondary" onClick={() => setOwnedOpen(true)}><LibraryBig size={17} />{isLibrary ? 'Số bản sách thư viện' : `Sách mình có (${user.owned.length})`}</button></SectionHeading>
    <div className="community-banner"><HeartHandshake size={34} /><div><h3>{isLibrary ? 'Ưu tiên đúng sách, đúng buổi học.' : 'Một lời đồng ý, một buổi học trọn vẹn.'}</h3><p>{isLibrary ? 'Kiểm tra số bản trước khi đề nghị. Học sinh cần xác nhận để giữ sách.' : 'Bảng yêu cầu mở cho mọi tài khoản. Chọn một lời nhờ phù hợp và gửi đề nghị của bạn.'}</p></div><span className="fee-badge">{isLibrary ? 'Miễn phí' : '10.000đ / lượt'}</span></div>
    <div className="tabs"><button className={tab === 'board' ? 'active' : ''} onClick={() => setTab('board')}>{isLibrary ? 'Yêu cầu mới' : 'Bảng yêu cầu'} <span>{board.length}</span></button><button className={tab === 'mine' ? 'active' : ''} onClick={() => setTab('mine')}>{isLibrary ? 'Đã xử lý' : 'Tôi đã đề nghị'} <span>{history.length}</span></button></div>
    <div className="loan-filters"><Search size={19} /><select aria-label="Lọc yêu cầu theo sách" value={bookFilter} onChange={e => setBookFilter(e.target.value)}><option value="">Tất cả sách</option>{books.map(b => <option key={b.id} value={b.id}>{b.title}</option>)}</select><input type="date" aria-label="Lọc theo ngày mượn" value={dateFilter} onChange={e => setDateFilter(e.target.value)} /><select aria-label="Lọc theo tiết" value={periodFilter} onChange={e => setPeriodFilter(e.target.value)}><option value="">Tất cả tiết</option>{periods.map((_, i) => <option key={i} value={i + 1}>Tiết {i + 1}</option>)}</select>{(bookFilter || dateFilter || periodFilter) && <button className="text-button" onClick={() => { setBookFilter(''); setDateFilter(''); setPeriodFilter(''); }}>Xóa bộ lọc</button>}</div>
    <div className="requests-grid">{shown.map(r => <RequestCard key={r.id} request={r} />)}</div>{!shown.length && <Empty title="Chưa có yêu cầu ở đây" text="Thử thay đổi bộ lọc hoặc quay lại khi có lời nhờ mới." />}
    {ownedOpen && <Modal title={isLibrary ? 'Số bản sách thư viện' : 'Những cuốn sách bạn có'} onClose={() => setOwnedOpen(false)}><p className="muted">{isLibrary ? 'Số bản tổng của thư viện trong bộ dữ liệu mẫu. Các lượt đã xác nhận được tính khi kiểm tra còn sách.' : 'Khai báo đúng sách và bộ sách. Mỗi lựa chọn tương ứng một bản sách có thể cho mượn.'}</p><div className="owned-list">{books.map(b => <div key={b.id}><span><strong>{b.title}</strong><small>{b.series} · {b.volume}</small></span>{isLibrary ? <span className="stock-count">{db.stock[b.id] || 0} bản</span> : <label className="switch-label"><input type="checkbox" checked={user.owned.includes(b.id)} aria-label={`Tôi có ${b.title}`} onChange={() => commit(state => toggleOwned(state, user.id, b.id))} /><span className="switch-track" /></label>}</div>)}</div><button className="button primary full" onClick={() => setOwnedOpen(false)}>Xong <Check size={17} /></button></Modal>}
  </>;
}
function RequestCard({ request: r }: { request: BorrowRequest; }) {
  const { db, user, commit } = useApp(); const [offering, setOffering] = useState(false); const [cancelling, setCancelling] = useState(false);
  const book = books.find(b => b.id === r.bookId)!; const borrower = db.users.find(u => u.id === r.borrowerId)!;
  const mine = r.borrowerId === user.id; const offers = db.offers.filter(o => o.requestId === r.id); const pending = offers.filter(o => o.status === 'pending'); const accepted = offers.find(o => o.id === r.offerId); const myOffer = offers.find(o => o.lenderId === user.id);
  const canOffer = r.status === 'open' && !mine && !myOffer && available(db, user, r); const lender = accepted && db.users.find(u => u.id === accepted.lenderId); const isLender = lender?.id === user.id;
  const overdue = ['matched', 'received'].includes(r.status) && endAt(r) < Date.now(); const fit = r.target === 'community' && matchesSchedule(db, user, r);
  function submitOffer(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const form = new FormData(e.currentTarget); if (commit(state => offerBook(state, user.id, r.id, String(form.get('location'))), 'Đã gửi đề nghị. Hãy chờ người mượn xác nhận.')) setOffering(false); }
  return <article className="request-card"><div className="row between"><span className={`status ${overdue ? 'overdue' : r.status}`}>{overdue ? 'Quá hạn · chưa trả' : statusNames[r.status]}</span><span className="request-channel">{r.target === 'library' ? <LibraryBig size={14} /> : <Users size={14} />} {r.target === 'library' ? 'Thư viện' : 'Cộng đồng'}</span></div><div className="request-book"><span className={`subject-icon ${book.color}`}>{book.subject.slice(0, 1)}</span><div><h3>{book.title}</h3><p>{book.series} · {book.volume}</p></div></div><div className="request-schedule"><span><CalendarDays size={15} />{formatDate(r.date)}</span><span><Clock3 size={15} />Tiết {r.start}{r.end !== r.start ? `–${r.end}` : ''} · {periods[r.start - 1].start}–{periods[r.end - 1].end}</span></div>{r.note && <p className="request-note">“{r.note}”</p>}<div className="request-person"><span className="mini-avatar">{borrower.name.split(' ').at(-1)?.charAt(0)}</span><div>{borrower.name}<small>{borrower.role === 'guest' ? 'Tài khoản khách' : borrower.classroom.split(' · ')[0]}{mine ? ' · Bạn' : ''}</small></div><span className="price">{r.target === 'library' ? 'Miễn phí' : '10.000đ'}<small>{r.target === 'library' ? 'Tại thư viện' : 'Trả trực tiếp'}</small></span></div>
    {fit && r.status === 'open' && <div className="fit-note"><Check size={14} /> Bạn có sách và lịch học phù hợp</div>}
    {r.reason && <p className="fine">Lý do: {r.reason}</p>}
    {mine && r.status === 'open' && pending.length > 0 && <div className="offer-list"><strong>{pending.length} lời đề nghị cho bạn</strong>{pending.map(o => <div key={o.id}><p><b>{db.users.find(u => u.id === o.lenderId)?.name}</b><span><MapPin size={13} />{o.location}</span></p><button className="button primary compact" onClick={() => commit(state => acceptOffer(state, user.id, o.id), 'Đã xác nhận. Thông tin giao nhận đã được gửi cho hai bên.')}>Xác nhận mượn</button></div>)}</div>}
    {accepted && (mine || isLender) && <div className="handover-info"><span><MapPin size={16} /><strong>{accepted.location}</strong></span><p>{mine ? `Người cho mượn: ${lender?.name}` : `Người mượn: ${borrower.name}`}<br />Nhận trước {periods[r.start - 1].start}, trả lúc {periods[r.end - 1].end}. {r.target === 'library' ? 'Không thu phí.' : '10.000đ/lượt, hai bên thanh toán trực tiếp.'}</p></div>}
    <div className="request-actions">
      {!mine && r.status === 'open' && !myOffer && <button className="button primary full" disabled={!canOffer} onClick={() => setOffering(true)}><HeartHandshake size={16} />{canOffer ? 'Mình có thể cho mượn' : user.role === 'library' ? 'Không còn bản khả dụng' : !user.owned.includes(r.bookId) ? 'Khai báo sách mình có để cho mượn' : 'Sách đang có lịch mượn'}</button>}
      {!mine && myOffer?.status === 'pending' && <div className="waiting"><Clock3 size={16} /> Đã đề nghị · Chờ người mượn xác nhận</div>}
      {!mine && myOffer?.status === 'closed' && <p className="fine">Đề nghị của bạn đã đóng.</p>}
      {mine && r.status === 'open' && !pending.length && <div className="waiting"><Clock3 size={16} /> Đang chờ lời hồi đáp</div>}
      {mine && r.status === 'matched' && <button className="button primary full" onClick={() => commit(state => changeRequest(state, user.id, r.id, 'receive'), 'Đã ghi nhận bạn nhận được sách.')}>Mình đã nhận sách <Check size={17} /></button>}
      {isLender && r.status === 'received' && <button className="button primary full" onClick={() => commit(state => changeRequest(state, user.id, r.id, 'return'), 'Đã xác nhận trả sách. Cảm ơn bạn đã chia sẻ!')}>Xác nhận đã nhận lại sách <Check size={17} /></button>}
      {mine && r.status === 'received' && <p className="fine">Người cho mượn sẽ xác nhận khi nhận lại sách.</p>}
      {mine && ['open', 'matched'].includes(r.status) && <button className="text-button cancel-link" onClick={() => setCancelling(true)}>Hủy yêu cầu / Đã có sách</button>}
      {user.role === 'library' && r.status === 'open' && <button className="text-button cancel-link" onClick={() => commit(state => changeRequest(state, user.id, r.id, 'reject'), 'Đã thông báo thư viện chưa thể hỗ trợ.')}>Từ chối · chưa thể hỗ trợ</button>}
    </div>
    {offering && <Modal title={`Cho mượn ${book.title}`} onClose={() => setOffering(false)}><p>Bạn đề nghị cho <strong>{borrower.name}</strong> mượn ngày {formatDate(r.date)}, tiết {r.start}–{r.end}.</p><form onSubmit={submitOffer}><label>Địa điểm nhận và trả trong trường<input name="location" required maxLength={120} defaultValue={user.classroom} placeholder="Ví dụ: Sảnh khu A, cạnh phòng thư viện" /></label><div className="info-box">{user.role === 'library' ? 'Miễn phí, nhận tại thư viện.' : 'Phí 10.000đ/lượt, thanh toán trực tiếp giữa hai bên.'} Sách chỉ được giữ sau khi người mượn xác nhận đề nghị này.</div><div className="modal-actions"><button type="button" className="button secondary" onClick={() => setOffering(false)}>Quay lại</button><button type="submit" className="button primary">Gửi đề nghị <Send size={16} /></button></div></form></Modal>}
    {cancelling && <Modal title="Hủy yêu cầu mượn sách?" onClose={() => setCancelling(false)}><form onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); if (commit(state => changeRequest(state, user.id, r.id, 'cancel', String(f.get('reason'))), 'Đã hủy yêu cầu và thông báo tới người đã đề nghị.')) setCancelling(false); }}><label>Lý do<select name="reason"><option>Đã có sách chính thức</option><option>Thay đổi lịch học</option><option>Không còn nhu cầu</option></select></label><p className="fine">Yêu cầu được lưu trong lịch sử và không xuất hiện trên bảng chung nữa.</p><div className="modal-actions"><button type="button" className="button secondary" onClick={() => setCancelling(false)}>Giữ yêu cầu</button><button className="button primary" type="submit">Xác nhận hủy</button></div></form></Modal>}
  </article>;
}
