import { useState } from 'react';
import type { FormEvent } from 'react';
import { ArrowRight, Bell, BookOpen, CalendarDays, CheckCheck, CircleHelp, LogOut, Mail, RotateCcw, Settings, ShieldCheck, Sparkles } from 'lucide-react';
import { useApp } from '../context';
import { periods, saveSettings } from '../domain';
import { Empty, SectionHeading } from '../components';

export function SchedulePage() {
  const { user, go } = useApp();
  if (user.role !== 'student') return <><SectionHeading eyebrow="LỊCH HỌC TỪ NHÀ TRƯỜNG" title="Thời khóa biểu" text="Biết lịch học để chia sẻ sách vào đúng lúc." /><Empty title={user.role === 'guest' ? 'Lịch học dành cho tài khoản trường' : 'Thư viện không có lịch học cá nhân'} text={user.role === 'guest' ? 'Khách vẫn xem được toàn bộ yêu cầu cộng đồng và chủ động cho mượn. Liên hệ trường để được cấp tài khoản có thời khóa biểu và gợi ý tự động.' : 'Kiểm tra ngày và tiết của từng yêu cầu trong bàn thư viện.'}><button className="button primary" onClick={() => go('lend')}>Xem yêu cầu mượn <ArrowRight size={16} /></button></Empty></>;
  return <><SectionHeading eyebrow="CHUẨN BỊ CHO MỖI BUỔI HỌC" title="Thời khóa biểu" text="Lịch học giúp Cầu Sách kết nối sách của bạn với người đang cần." /><div className="schedule-header"><span className="quick-icon"><CalendarDays size={24} /></span><div><h3>{user.classroom}</h3><p>Lịch tuần mẫu · Do nhà trường cung cấp</p></div><span className="source-label"><ShieldCheck size={14} /> Dữ liệu mô phỏng</span></div><div className="schedule-table-wrap"><table className="schedule-table"><caption className="sr-only">Thời khóa biểu mẫu của {user.name}</caption><thead><tr><th scope="col">Tiết / Giờ</th>{[2, 3, 4, 5, 6].map(d => <th scope="col" key={d}>Thứ {d}</th>)}</tr></thead><tbody>{periods.map((p, i) => <tr key={i}><th scope="row"><strong>Tiết {i + 1}</strong><span>{p.start}–{p.end}</span></th>{[1, 2, 3, 4, 5].map(day => <td key={day}><span className={`lesson ${user.schedule[day]?.[i] === 'Toán' ? 'math-lesson' : ''}`}>{user.schedule[day]?.[i] || 'Trống'}</span></td>)}</tr>)}</tbody></table></div><div className="info-box row"><Sparkles size={22} /><p>Khi bạn có đúng sách và không học môn đó trong khoảng tiết được yêu cầu, Cầu Sách gửi gợi ý cho mượn. Bạn luôn tự quyết định có đồng ý hay không.</p></div><p className="fine">Lịch chuông mẫu: 8 tiết/ngày, từ thứ Hai đến thứ Sáu, múi giờ Việt Nam. Chức năng nhập dữ liệu của nhà trường sẽ được kết nối ở bản triển khai thật.</p></>;
}
export function NotificationsPage() {
  const { db, user, commit, go } = useApp(); const [tab, setTab] = useState('notifications');
  const notices = db.notices.filter(n => n.userId === user.id); const mails = db.mails.filter(m => m.userId === user.id);
  const datetime = (s: string) => new Intl.DateTimeFormat('vi-VN', { day: '2-digit', month: '2-digit', hour: '2-digit', minute: '2-digit', timeZone: 'Asia/Ho_Chi_Minh' }).format(new Date(s));
  return <><SectionHeading eyebrow="NHỮNG LỜI HỒI ĐÁP" title="Thông báo" text="Một lời đề nghị mới, một cuốn sách đã được kết nối."><button className="button secondary" onClick={() => commit(state => ({ ...state, notices: state.notices.map(n => n.userId === user.id ? { ...n, read: true } : n) }), 'Đã đánh dấu tất cả là đã đọc.')}><CheckCheck size={17} /> Đánh dấu đã đọc</button></SectionHeading><div className="tabs"><button className={tab === 'notifications' ? 'active' : ''} onClick={() => setTab('notifications')}>Trong ứng dụng <span>{notices.length}</span></button><button className={tab === 'mail' ? 'active' : ''} onClick={() => setTab('mail')}>Hộp thư mô phỏng <span>{mails.length}</span></button></div>
    {tab === 'notifications' ? <>{notices.length ? <div className="notice-list">{notices.map(n => <button className={`notice ${n.read ? '' : 'new'}`} key={n.id} onClick={() => { commit(state => ({ ...state, notices: state.notices.map(item => item.id === n.id ? { ...item, read: true } : item) })); const r = db.requests.find(r => r.id === n.requestId); go(r?.borrowerId === user.id ? 'borrow' : 'lend'); }}><span className={`notice-icon ${n.kind === 'suggestion' ? 'suggestion' : ''}`}>{n.kind === 'suggestion' ? <Sparkles size={21} /> : <Bell size={21} />}</span><div><div className="row between"><strong>{n.title}</strong><time>{datetime(n.createdAt)}</time></div><p>{n.body}</p><span className="notice-link">Xem mục {db.requests.find(r => r.id === n.requestId)?.borrowerId === user.id ? 'Mượn sách' : 'Cho mượn'} <ArrowRight size={13} /></span></div>{!n.read && <span className="notice-unread" />}</button>)}</div> : <Empty title="Chưa có thông báo mới" text="Lời đề nghị và xác nhận mượn sách sẽ xuất hiện ở đây." />}</> : <><div className="info-box"><strong>Email demo — không gửi thư thật.</strong><p>Bật nhận email trong cài đặt, sau đó thực hiện một giao dịch để xem thư được tạo ở đây. Email trước lúc bật sẽ không gửi lại.</p><button className="text-button" onClick={() => go('settings')}>Đi tới cài đặt email <ArrowRight size={15} /></button></div>{mails.length ? <div className="notice-list">{mails.map(m => <article className="notice mail-card" key={m.id}><span className="notice-icon"><Mail size={21} /></span><div><div className="row between"><strong>{m.title}</strong><time>{datetime(m.createdAt)}</time></div><small>Đến: {m.to} · Mô phỏng</small><p>{m.body}</p></div></article>)}</div> : <Empty title="Hộp thư demo đang trống" text="Thêm email và bật nhận thư để thử luồng thông báo qua email." />}</>}
  </>;
}
export function SettingsPage() {
  const { user, commit, showIntro, showTour, reset, logout } = useApp();
  return <SettingsForm key={user.id} userId={user.id} initialEmail={user.email} initialEnabled={user.emailEnabled} onSave={(email, enabled) => commit(db => saveSettings(db, user.id, email, enabled), 'Đã lưu tùy chọn thông báo.')}><SectionHeading eyebrow="GÓC RIÊNG CỦA BẠN" title="Cài đặt" text="Tùy chỉnh cách bạn nhận những lời hồi đáp." /><section className="settings-profile"><span className="avatar large">{user.name.split(' ').at(-1)?.charAt(0)}</span><div><h3>{user.name}</h3><p>@{user.username} · {user.role === 'guest' ? 'Tài khoản khách' : user.role === 'library' ? 'Tài khoản thư viện' : user.classroom}</p></div><span className="source-label">{user.role === 'guest' ? 'Tự tạo trong demo' : 'Nhà trường cấp'}</span></section><div className="settings-help"><h3><CircleHelp size={20} /> Hướng dẫn & prototype</h3><button onClick={showIntro}><span><BookOpen size={19} />Đọc giới thiệu và giới hạn</span><ArrowRight size={17} /></button><button onClick={showTour}><span><Sparkles size={19} />Xem lại hướng dẫn giao diện</span><ArrowRight size={17} /></button><button onClick={logout}><span><LogOut size={19} />Đăng xuất khỏi tài khoản</span><ArrowRight size={17} /></button><button onClick={reset}><span><RotateCcw size={19} />Khôi phục dữ liệu demo</span><ArrowRight size={17} /></button></div></SettingsForm>;
}
function SettingsForm({ children, initialEmail, initialEnabled, onSave }: { children: React.ReactNode; userId: string; initialEmail: string; initialEnabled: boolean; onSave: (email: string, enabled: boolean) => boolean; }) {
  const [email, setEmail] = useState(initialEmail); const [enabled, setEnabled] = useState(initialEnabled);
  function submit(e: FormEvent) { e.preventDefault(); onSave(email, enabled); }
  return <div className="settings-layout">{children}<section className="settings-email"><h3><Mail size={21} /> Thông báo qua email</h3><p>Nhận thông tin đề nghị, xác nhận và thay đổi lượt mượn. Học sinh có thể nhận thêm gợi ý theo lịch; khách chỉ nhận thông báo giao dịch.</p><form onSubmit={submit}><label>Email cá nhân<input type="email" value={email} required={enabled} onChange={e => setEmail(e.target.value)} placeholder="Ví dụ: ban@example.com" maxLength={120} /></label><label className="email-toggle"><span><strong>Nhận thông báo qua email</strong><small>Thư xuất hiện trong hộp thư mô phỏng</small></span><span className="switch-label"><input type="checkbox" checked={enabled} onChange={e => setEnabled(e.target.checked)} /><span className="switch-track" /></span></label><div className="info-box">Prototype không gửi email ra ngoài. Có thể dùng email mẫu như <b>ban@example.com</b> để kiểm tra.</div><button className="button primary" type="submit"><Settings size={16} /> Lưu cài đặt</button></form></section></div>;
}
