import { useEffect, useId, useRef, useState } from 'react';
import type { ReactNode } from 'react';
import { ArrowLeft, ArrowRight, BookOpen, Check, ChevronRight, ExternalLink, HeartHandshake, Leaf, ShieldCheck, X } from 'lucide-react';
import type { Book, Page } from './types';

export function Logo() { return <span className="brand"><span className="brand-icon"><BookOpen size={23} strokeWidth={1.7} /></span><span>Cầu Sách<span className="brand-dot">.</span></span></span>; }
export function Modal({ title, children, onClose, wide = false }: { title: string; children: ReactNode; onClose: () => void; wide?: boolean; }) {
  const ref = useRef<HTMLDialogElement>(null); const label = useId();
  useEffect(() => { const d = ref.current!; d.showModal(); return () => d.close(); }, []);
  return <dialog ref={ref} aria-labelledby={label} onCancel={e => { e.preventDefault(); onClose(); }} className={`modal ${wide ? 'wide' : ''}`}>
    <div className="modal-heading"><h2 id={label}>{title}</h2><button className="icon-button" onClick={onClose} aria-label="Đóng cửa sổ"><X size={20} /></button></div>{children}
  </dialog>;
}
export function Intro({ onClose }: { onClose: () => void; }) {
  return <Modal title="Chào mừng đến Cầu Sách" onClose={onClose} wide><div className="intro-banner"><span className="eyebrow">MỘT CUỐN SÁCH · NHIỀU CƠ HỘI</span><h3>Việc học tiếp nối.<br />Nhờ chúng mình kết nối.</h3><BookOpen size={78} strokeWidth={1} /></div>
    <p className="intro-description">Một trạm hỗ trợ nhỏ trong thời gian chờ sách chính thức. Đọc từ nguồn tin cậy, tìm sách cần mượn và chia sẻ sách bạn đang có.</p>
    <div className="intro-grid"><div><ShieldCheck /><strong>Nhà trường đồng hành</strong><p>Tài khoản, lớp học, lịch chuông, thời khóa biểu và danh mục sách do nhà trường cung cấp khi triển khai thực tế.</p></div><div><ExternalLink /><strong>Đọc đúng nguồn</strong><p>Liên kết tới trang sách chính chủ. Không lưu trữ, scan hay phát hành lại sách giáo khoa.</p></div><div><HeartHandshake /><strong>Chia sẻ có trách nhiệm</strong><p>Cá nhân thu 10.000đ/lượt, trả trực tiếp. Thư viện miễn phí. Quy trình và mức phí cần trường chấp thuận khi áp dụng.</p></div><div><Leaf /><strong>Bạn đang xem prototype</strong><p>Dữ liệu lưu trên trình duyệt. Tài khoản, thời khóa biểu và email đều mô phỏng. Không nhập mật khẩu thật.</p></div></div>
    <div className="info-box">Khách vẫn có thể mượn/cho mượn và nhận thông báo giao dịch. Tài khoản trường có thêm thư viện, thời khóa biểu và gợi ý cho mượn phù hợp.</div>
    <button className="button primary full" onClick={onClose}>Mình đã hiểu, bắt đầu thôi <ArrowRight size={17} /></button><p className="fine center">Mở lại phần giới thiệu bất cứ lúc nào tại mục Trợ giúp.</p>
  </Modal>;
}
export function BookArt({ book, small = false }: { book: Book; small?: boolean; }) {
  return <div className={`book-art ${book.color} ${small ? 'small' : ''}`} aria-hidden="true"><div className="book-topline">CẦU SÁCH <span>HỌC LIỆU</span></div><div className="book-art-title">{book.subject}<span>{book.grade}</span></div>
    <svg viewBox="0 0 260 150" fill="none" className="book-drawing">
      {book.symbol === 'math' ? <><circle cx="163" cy="76" r="58" fill="currentColor" opacity=".15" /><path d="M36 122 107 19 178 122Z" stroke="currentColor" strokeWidth="2" /><path d="M108 19v103M36 122l144-66M16 133h224" stroke="currentColor" opacity=".55" /><circle cx="178" cy="56" r="6" fill="currentColor" /><text x="194" y="126" fontSize="36" fill="currentColor" fontFamily="Georgia">π</text></> : book.symbol === 'literature' ? <><path d="M36 109q45-32 89 0V37Q78 7 36 39v70ZM214 109q-45-32-89 0V37q47-30 89 2v70Z" fill="currentColor" opacity=".16" /><path d="M36 109q45-32 89 0V37Q78 7 36 39v70ZM214 109q-45-32-89 0V37q47-30 89 2v70Z" stroke="currentColor" strokeWidth="2" /><path d="m151 120 42-88m-22 45q29-1 43-38-36 4-43 38" stroke="currentColor" strokeWidth="2" /></> : book.symbol === 'physics' ? <><circle cx="130" cy="75" r="12" fill="currentColor" /><ellipse cx="130" cy="75" rx="87" ry="31" stroke="currentColor" strokeWidth="2" /><ellipse cx="130" cy="75" rx="87" ry="31" stroke="currentColor" strokeWidth="2" transform="rotate(60 130 75)" /><ellipse cx="130" cy="75" rx="87" ry="31" stroke="currentColor" strokeWidth="2" transform="rotate(-60 130 75)" /><circle cx="212" cy="63" r="7" fill="currentColor" /></> : book.symbol === 'chemistry' ? <><path d="M102 19h52m-43 0v48l-43 58q-7 12 9 12h108q16 0 9-12l-48-58V19" stroke="currentColor" strokeWidth="2" /><path d="M99 92h66l27 40H72Z" fill="currentColor" opacity=".2" /><circle cx="126" cy="100" r="6" fill="currentColor" /><circle cx="143" cy="78" r="3" fill="currentColor" /></> : book.symbol === 'biology' ? <><path d="M130 132V39m0 50Q58 86 57 28q70 0 73 61Zm0 26q73-4 73-61-67 0-73 61Z" stroke="currentColor" strokeWidth="2" /><path d="M130 89Q58 86 57 28q70 0 73 61Z" fill="currentColor" opacity=".16" /><path d="m79 49 51 49 53-27" stroke="currentColor" /></> : <><path d="M49 125h167M63 116h138M70 116V57h123v59M57 56h151l-76-39Z" stroke="currentColor" strokeWidth="2" /><path d="M82 63v45m25-45v45m25-45v45m25-45v45m25-45v45" stroke="currentColor" strokeWidth="8" opacity=".3" /></>}
    </svg><div className="book-bottomline">{book.volume}<span>Minh họa</span></div></div>;
}
export function HeroArt() { return <svg className="hero-art" viewBox="0 0 420 260" fill="none" aria-hidden="true"><circle cx="244" cy="127" r="112" fill="#e6ba76" opacity=".24" /><circle cx="270" cy="103" r="69" stroke="#d9e2bf" strokeDasharray="3 8" opacity=".5" /><path d="M98 203q148 37 248-2" stroke="#a1b89b" /><g transform="rotate(-12 230 152)"><rect x="120" y="102" width="174" height="112" rx="7" fill="#d3bca1" /><rect x="130" y="91" width="173" height="112" rx="6" fill="#f6e9cf" /><path d="M140 106h146m-146 9h146m-146 9h146" stroke="#c1aa88" opacity=".6" /><rect x="111" y="83" width="181" height="107" rx="7" fill="#da8d69" /><rect x="126" y="83" width="2" height="107" fill="#ae674e" /><path d="M161 126q32-27 68 3m-68 8q32-27 68 3" stroke="#f5d7b7" strokeWidth="3" /></g><g transform="rotate(12 257 106)"><path d="M172 42q39-15 78 8 36-27 76-18v119q-37-8-76 18-39-21-78-8Z" fill="#faf3df" /><path d="M250 50v119" stroke="#baaa8b" /><path d="M184 65q29-10 52 6m-52 7q29-10 52 6m-52 7q29-10 52 6m29-34q21-15 43-14m-43 27q21-15 43-14m-43 27q21-15 43-14" stroke="#c6bba1" strokeWidth="2" /><path d="M289 37v53l9-12 9 6V32" fill="#e2a96e" /></g><path d="m101 133-9-19m13 0-15 11m248 32 15-5m-8-8 2 17" stroke="#ddc8a5" strokeWidth="2" /><circle cx="135" cy="54" r="4" fill="#dcab78" /><circle cx="342" cy="84" r="3" fill="#dfc491" /><path d="M71 198q-8-37-32-43 0 35 32 43Zm0 0q29-43 10-61-22 26-10 61Z" fill="#94ac83" /><path d="m64 184 10 36" stroke="#c6d0ad" strokeWidth="3" /></svg>; }
export function Empty({ title, text, children }: { title: string; text: string; children?: ReactNode; }) { return <div className="empty"><span className="empty-icon"><BookOpen size={29} /></span><h3>{title}</h3><p>{text}</p>{children}</div>; }
export function SectionHeading({ eyebrow, title, text, children }: { eyebrow: string; title: string; text: string; children?: ReactNode; }) { return <div className="section-heading"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{text}</p></div>{children}</div>; }
const steps: { target: string; page: Page; title: string; text: string; }[] = [
  { target: 'books', page: 'books', title: 'Bắt đầu từ một cuốn sách', text: 'Chọn sách và mở nguồn chính thức của nhà xuất bản. Bộ lọc giúp tìm đúng sách bạn đang học.' },
  { target: 'borrow', page: 'borrow', title: 'Cần sách cho buổi học tới?', text: 'Tạo yêu cầu theo ngày và khoảng tiết. Gửi đến cộng đồng hoặc thư viện nếu bạn có tài khoản trường.' },
  { target: 'lend', page: 'lend', title: 'Bạn có sách, ai đó đang cần', text: 'Xem yêu cầu công khai, khai báo sách mình có và đề nghị cho mượn. Người mượn xác nhận để hoàn tất kết nối.' },
  { target: 'schedule', page: 'schedule', title: 'Kết nối theo thời khóa biểu', text: 'Lịch do trường cung cấp giúp gợi ý đúng người có thể cho mượn. Khách vẫn chủ động xem mọi yêu cầu cộng đồng.' },
  { target: 'notifications', page: 'notifications', title: 'Không bỏ lỡ một lời hồi đáp', text: 'Cả khách và học sinh đều nhận thông báo giao dịch. Vào cài đặt để bật email và xem hộp thư mô phỏng.' },
];
export function Tour({ navigate, onClose }: { navigate: (p: Page) => void; onClose: () => void; }) {
  const [step, setStep] = useState(0); const [rect, setRect] = useState<DOMRect | null>(null); const panel = useRef<HTMLDivElement>(null);
  useEffect(() => {
    navigate(steps[step].page);
    const position = () => { const target = document.querySelector(`[data-tour="${steps[step].target}"]`); if (target) setRect(target.getBoundingClientRect()); };
    const t = window.setTimeout(position, 80); window.addEventListener('resize', position); panel.current?.focus();
    return () => { window.clearTimeout(t); window.removeEventListener('resize', position); };
  }, [step, navigate]);
  return <div className="tour-layer" role="dialog" aria-modal="true" aria-labelledby="tour-title" onKeyDown={e => {
    if (e.key === 'Escape') onClose();
    if (e.key === 'Tab') { const nodes = panel.current!.querySelectorAll<HTMLButtonElement>('button'); const first = nodes[0], last = nodes[nodes.length - 1]; if (e.shiftKey && (document.activeElement === first || document.activeElement === panel.current)) { e.preventDefault(); last.focus(); } else if (!e.shiftKey && document.activeElement === last) { e.preventDefault(); first.focus(); } }
  }}><div className="tour-shade" />{rect && <div className="tour-spotlight" style={{ top: rect.top - 5, left: rect.left - 5, width: rect.width + 10, height: rect.height + 10 }} />}<div className="tour-card" ref={panel} tabIndex={-1}><div className="row between"><span className="eyebrow">KHÁM PHÁ CẦU SÁCH · {step + 1}/5</span><button className="text-button" onClick={onClose}>Bỏ qua</button></div><h2 id="tour-title">{steps[step].title}</h2><p>{steps[step].text}</p><div className="row between"><div className="tour-dots">{steps.map((_, i) => <span key={i} className={i === step ? 'active' : ''} />)}</div><div className="row">{step > 0 && <button className="icon-button" aria-label="Bước trước" onClick={() => setStep(step - 1)}><ArrowLeft size={19} /></button>}<button className="button primary" onClick={() => step === steps.length - 1 ? onClose() : setStep(step + 1)}>{step === steps.length - 1 ? 'Khám phá thôi' : 'Tiếp theo'}{step === steps.length - 1 ? <Check size={17} /> : <ChevronRight size={17} />}</button></div></div></div></div>;
}
